version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "barabashka"
      MYSQL_LOG_CONSOLE: "true"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
  web:
    build: Client
    volumes:
       - ./Client:/src
    environment:
      NODE_ENV: production
    depends_on:
      - mysql
      - nodeserver
    ports:
      - "8080:80"
  nodeserver:
    build:
      context: ./Server
    environment:
      DB_HOST: mysql
      DB_PASS: barabashka
      DB_DATABASE: tiny_url
      NODE_ENV: production
    depends_on:
      - mysql
volumes:
  mysql_data:
